name: Run Auth Tests
on:
  workflow_dispatch:

jobs:
  publish:
    name: Authentication Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build vars collection
        id: "build-vars"
        if: ${{ ! cancelled() }}
        env:
          ALL_VARS: ${{ secrets.ALL_VARS }}
        run: |
          chmod +x ./scans/auth/*.sh
          ./scans/auth/collect_vars.sh
      - name: Authentication plan tests
        id: "test-auth-plans"
        if: ${{ ! cancelled() }}
        run: |
          chmod a+w $(pwd)
          docker pull ghcr.io/zaproxy/zaproxy:nightly
          docker run --rm -v $(pwd):/zap/wrk/:rw --env-file scans/auth/all_vars.env -t zaproxy/zap-nightly /zap/wrk/scans/auth/auth_plan_tests.sh 
