on:
  workflow_dispatch:

name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Do stuff
        run: |
          shopt -s extglob
          BASE=$(pwd)
          echo $BASE
          touch stuff/all_vars.env
          cd stuff
          for d in **/; do
            echo $d
            echo "SECRET_NAME=$d_DIR" >> $GITHUB_ENV
            # echo "SECRET_NAME = ${{ env.SECRET_NAME }}"
            echo "VALUE=${{ secrets[env.SECRET_NAME] }}" >> $GITHUB_ENV
            if [[ ! -f "$d/vars.env" ]];
            then
              echo One
              # Here we'd get values from the secrets store
              cd ${{ env.VALUE }}
              pwd
              ls
              cd ../
           else
             echo Two
             echo $d
             cat "$d"/vars.env | tee -a stuff/all_vars.env > /dev/null
           fi
          done
