on:
  workflow_dispatch:

name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Do stuff
        run: |
          cd stuff
          for d in **/; do
            echo $d
            echo "SECRET_NAME=$d_DIR" >> $GITHUB_ENV
            echo "SECRET_NAME = ${{ env.SECRET_NAME }}"
            if ! [[ -s "$d/vars.env" ]];
            then
              # Here we'd get values from the secrets store
              LOC="$d"_DIR
              cd ./stuff/${{ secrets[env.SECRET_NAME] }}
              pwd
              ls
           else
             cat "$d"/vars.env | tee -a ./scans/auth/all_vars.env > /dev/null
           fi
          done

