on:
  workflow_dispatch:

name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Do stuff
        run: |
          shopt -s extglob
          BASE=$(pwd)
          echo $BASE
          touch $BASE/stuff/all_vars.env
          cd stuff
          for d in **/; do
            echo $d
            echo "NAME=$d_DIR" >> $GITHUB_ENV
            echo "NAME = ${{ env.NAME }}"
            #echo "VALUE=${{ secrets[env.NAME] }}" >> $GITHUB_ENV
            if [[ ! -f "$d/vars.env" ]];
            then
              echo One
              cd $d
              echo ${{ secrets[env.NAME] }} | tee -a $BASE/stuff/all_vars.env > /dev/null
              pwd
              ls -al
              cd ../
           else
             echo Two
             echo $d
             cat "$d"/vars.env | tee -a $BASE/stuff/all_vars.env > /dev/null
           fi
          done
          wc -l $BASE/stuff/all_vars.env
