on:
  workflow_dispatch:

name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Do stuff
        run: |
          BASE=$(pwd)
          cd stuff
          for d in **/; do
            echo $d
            echo "SECRET_NAME=$d_DIR" >> $GITHUB_ENV
            # echo "SECRET_NAME = ${{ env.SECRET_NAME }}"
            VALUE=${{ secrets[env.SECRET_NAME] }}
            if ! [[ -s "$d/vars.env" ]];
            then
              # Here we'd get values from the secrets store
              cd $VALUE
              pwd
              ls
              cd ../
           else
             echo $d
             cat "$d"/vars.env | tee -a $BASE/scans/auth/all_vars.env > /dev/null
           fi
          done
