on:
  workflow_dispatch:

name: Test
jobs:
  LinkCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Do stuff
        run: |
          for d in ./stuff/**/; do
            echo $d
            if ! [[ -s "$d/vars.env" ]];
            then
              # Here we'd get values from the secrets store
              cd ./stuff/${{ secrets.$d_dir }}
              pwd
              ls
           else
             cat "$d"/vars.env | tee -a ./scans/auth/all_vars.env > /dev/null
           fi
          done

